// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: rpc_login_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginUserRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username    *string                `protobuf:"bytes,1,opt,name=username"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_rpc_login_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_login_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginUserRequest) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginUserRequest) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginUserRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginUserRequest) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginUserRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginUserRequest) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Username = nil
}

func (x *LoginUserRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginUserRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username *string
	Password *string
}

func (b0 LoginUserRequest_builder) Build() *LoginUserRequest {
	m0 := &LoginUserRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Username = b.Username
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginUserResponse struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User                  *User                  `protobuf:"bytes,1,opt,name=user"`
	xxx_hidden_SessionId             *string                `protobuf:"bytes,2,opt,name=session_id,json=sessionId"`
	xxx_hidden_AccessToken           *string                `protobuf:"bytes,3,opt,name=access_token,json=accessToken"`
	xxx_hidden_RefreshToken          *string                `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken"`
	xxx_hidden_AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=access_token_expires_at,json=accessTokenExpiresAt"`
	xxx_hidden_RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_rpc_login_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_login_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginUserResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *LoginUserResponse) GetSessionId() string {
	if x != nil {
		if x.xxx_hidden_SessionId != nil {
			return *x.xxx_hidden_SessionId
		}
		return ""
	}
	return ""
}

func (x *LoginUserResponse) GetAccessToken() string {
	if x != nil {
		if x.xxx_hidden_AccessToken != nil {
			return *x.xxx_hidden_AccessToken
		}
		return ""
	}
	return ""
}

func (x *LoginUserResponse) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *LoginUserResponse) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_AccessTokenExpiresAt
	}
	return nil
}

func (x *LoginUserResponse) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_RefreshTokenExpiresAt
	}
	return nil
}

func (x *LoginUserResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *LoginUserResponse) SetSessionId(v string) {
	x.xxx_hidden_SessionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *LoginUserResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *LoginUserResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *LoginUserResponse) SetAccessTokenExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_AccessTokenExpiresAt = v
}

func (x *LoginUserResponse) SetRefreshTokenExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_RefreshTokenExpiresAt = v
}

func (x *LoginUserResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *LoginUserResponse) HasSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginUserResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LoginUserResponse) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *LoginUserResponse) HasAccessTokenExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessTokenExpiresAt != nil
}

func (x *LoginUserResponse) HasRefreshTokenExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RefreshTokenExpiresAt != nil
}

func (x *LoginUserResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

func (x *LoginUserResponse) ClearSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SessionId = nil
}

func (x *LoginUserResponse) ClearAccessToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AccessToken = nil
}

func (x *LoginUserResponse) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RefreshToken = nil
}

func (x *LoginUserResponse) ClearAccessTokenExpiresAt() {
	x.xxx_hidden_AccessTokenExpiresAt = nil
}

func (x *LoginUserResponse) ClearRefreshTokenExpiresAt() {
	x.xxx_hidden_RefreshTokenExpiresAt = nil
}

type LoginUserResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User                  *User
	SessionId             *string
	AccessToken           *string
	RefreshToken          *string
	AccessTokenExpiresAt  *timestamppb.Timestamp
	RefreshTokenExpiresAt *timestamppb.Timestamp
}

func (b0 LoginUserResponse_builder) Build() *LoginUserResponse {
	m0 := &LoginUserResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	if b.SessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_SessionId = b.SessionId
	}
	if b.AccessToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_AccessToken = b.AccessToken
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	x.xxx_hidden_AccessTokenExpiresAt = b.AccessTokenExpiresAt
	x.xxx_hidden_RefreshTokenExpiresAt = b.RefreshTokenExpiresAt
	return m0
}

var File_rpc_login_user_proto protoreflect.FileDescriptor

const file_rpc_login_user_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_login_user.proto\x12\x02pb\x1a\n" +
	"user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x10LoginUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xc0\x02\n" +
	"\x11LoginUserResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.pb.UserR\x04user\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12Q\n" +
	"\x17access_token_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12S\n" +
	"\x18refresh_token_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x15refreshTokenExpiresAtB\"Z github.com/rdozzi/simple_bank/pbb\beditionsp\xe9\a"

var file_rpc_login_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_login_user_proto_goTypes = []any{
	(*LoginUserRequest)(nil),      // 0: pb.LoginUserRequest
	(*LoginUserResponse)(nil),     // 1: pb.LoginUserResponse
	(*User)(nil),                  // 2: pb.User
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_rpc_login_user_proto_depIdxs = []int32{
	2, // 0: pb.LoginUserResponse.user:type_name -> pb.User
	3, // 1: pb.LoginUserResponse.access_token_expires_at:type_name -> google.protobuf.Timestamp
	3, // 2: pb.LoginUserResponse.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_login_user_proto_init() }
func file_rpc_login_user_proto_init() {
	if File_rpc_login_user_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_login_user_proto_rawDesc), len(file_rpc_login_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_login_user_proto_goTypes,
		DependencyIndexes: file_rpc_login_user_proto_depIdxs,
		MessageInfos:      file_rpc_login_user_proto_msgTypes,
	}.Build()
	File_rpc_login_user_proto = out.File
	file_rpc_login_user_proto_goTypes = nil
	file_rpc_login_user_proto_depIdxs = nil
}
